### ISSUE TITLE
doesn't work for Kinesis functions

### ISSUE THREAD

**Issue by theburningmonk** [functionalone/serverless-iam-roles-per-function#3] opened 2018-02-22 02:02 UTC
Just tried this one a project with some Kinesis functions, and as soon as these Kinesis functions are given per function IAM roles, the functions broke as the new role doesn't have the couple of permissions that the Serverless framework injects. 

You can see it in the console as something like this: 
`PROBLEM: User: arn:aws:sts::xxx:assumed-role/big-mouth-dev-notify-restaurant-us-east-1-lambdaRole/awslambda_783_20180222015150438 is not authorized to perform: kinesis:DescribeStream on resource: arn:aws:kinesis:us-east-1:xxx:stream/order-events`

I have tried setting default inherit to `true` but no vail.

It looks like the default role has these permissions:
```
"kinesis:GetRecords",
"kinesis:GetShardIterator",
"kinesis:DescribeStream",
"kinesis:ListStreams"
```
so I'd have thought inheriting the default role would have done the trick, but unfortunately not :-/

I haven't drilled into the difference in the CF template too much, but it seems that the serverless framework injects additional permissions (above) when it sees functions with Kinesis subscription.

**Comment by glicht** [comment] 2018-02-22 08:06
Thanks for reporting this. This is indeed a bug. The code doesn't handle the case of stream based resources which are based on polling (kinesis and dynamo streams).

Will investigate how to best add this.

**Comment by theburningmonk** [comment] 2018-02-22 12:57
Could you do something similar to what the Serverless framework does [here](https://github.com/serverless/serverless/blob/1f2d81126e5c064d8ab7410c34fecaaa50543ca4/lib/plugins/aws/package/compile/events/stream/index.js)? i.e. check if the function's event sources has a stream, and push the [relevant permissions](https://github.com/serverless/serverless/blob/1f2d81126e5c064d8ab7410c34fecaaa50543ca4/lib/plugins/aws/package/compile/events/stream/index.js#L168-L171) onto the CF template

**Comment by theburningmonk** [comment] 2018-02-22 13:00
Would this be a more general problem that the plug-in needs to solve around adding event specific permissions? Does it currently work with SNS event source?

**Comment by glicht** [comment] 2018-02-22 17:12
@theburningmonk, the fix will need to do something similar to what is done by serverless. The problem is only with stream based events which are based on polling, as they require additional permissions for the lambda role. SNS event source is not affected.

**Comment by glicht** [comment] 2018-02-23 17:32
Just pushed a fix which should resolve this. Also publish version 0.1.4 to npmjs with the fix.

**Closed by glicht** 2018-02-23 17:32 UTC
